.TH "COORDINATE" 3 "Sexta, 20 de Março de 2020" "Version 0.1" "SlimeTrail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COORDINATE \- Tipo de dados para as coordenadas\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data\&.h>\fP
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Tipo de dados para as coordenadas\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para SlimeTrail a partir do código fonte\&.
