.TH "C:/Users/Miguel Gomes/Documents/Miguel/Uni/LI2-TP1-G05/data.h" 3 "Sexta, 20 de Março de 2020" "Version 0.1" "SlimeTrail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Miguel Gomes/Documents/Miguel/Uni/LI2-TP1-G05/data.h
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "struct \fBCOORDINATE\fP"
.br
.RI "Tipo de dados para as coordenadas\&. "
.ti -1c
.RI "struct \fBMOVE\fP"
.br
.RI "Tipo de dados para a jogada\&. "
.ti -1c
.RI "struct \fBSTATE\fP"
.br
.RI "Tipo de dados para o estado\&. "
.in -1c
.SS "Definições de tipos"

.in +1c
.ti -1c
.RI "typedef \fBMOVE\fP \fBMOVES\fP[32]"
.br
.RI "Tipo de dados para as jogadas\&. "
.in -1c
.SS "Enumerações"

.in +1c
.ti -1c
.RI "enum \fBHOUSE\fP { \fBEMPTY\fP = '\&.', \fBWHITE\fP = '@', \fBBLACK\fP = '#', \fBH1\fP = '1', \fBH2\fP = '2' }"
.br
.RI "Tipo de dados para a casa\&. "
.in -1c
.SS "Funções"

.in +1c
.ti -1c
.RI "void \fBempty_board\fP (\fBHOUSE\fP[8][8])"
.br
.RI "Tabuleiro vazio\&. "
.ti -1c
.RI "\fBSTATE\fP * \fBstarting_state\fP ()"
.br
.RI "Inicializa o valor do estado Esta função inicializa o valor do estado\&. Isso implica o tabuleiro ser colocado na posição inicial e todos os campos do estado estarem com o valor por omissão\&. "
.ti -1c
.RI "int \fBget_current_player\fP (\fBSTATE\fP *)"
.br
.RI "Jogador Atual\&. "
.ti -1c
.RI "\fBHOUSE\fP \fBget_house\fP (\fBSTATE\fP *, \fBCOORDINATE\fP)"
.br
.RI "Devolve o valor de uma casa\&. "
.ti -1c
.RI "int \fBget_num_moves\fP (\fBSTATE\fP *)"
.br
.RI "Número de jogadas\&. "
.ti -1c
.RI "\fBCOORDINATE\fP \fBget_previous_move\fP (\fBSTATE\fP *)"
.br
.RI "Jogada anterior\&. "
.ti -1c
.RI "void \fBchange_house\fP (\fBSTATE\fP *, \fBCOORDINATE\fP, \fBHOUSE\fP)"
.br
.RI "Querido Mudei a Casa\&. "
.ti -1c
.RI "void \fBupdate_previous_move\fP (\fBSTATE\fP *, \fBCOORDINATE\fP)"
.br
.RI "Atualiza jogada anterior\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Definição do estado e das funções que o manipulam 
.SH "Documentação das funções"
.PP 
.SS "void change_house (\fBSTATE\fP *, \fBCOORDINATE\fP, \fBHOUSE\fP)"

.PP
Querido Mudei a Casa\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIe\fP Apontador para o estado 
.br
\fIc\fP A coordenada 
.br
\fIh\fP O valor da casa Esta função altera o valor da casa de uma certa coordenada\&. 
.RE
.PP

.SS "void empty_board (\fBHOUSE\fP[8][8])"

.PP
Tabuleiro vazio\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIt\fP Array do tabuleiro Esta função inicializa o array do tabuleiro\&. 
.RE
.PP

.SS "int get_current_player (\fBSTATE\fP *)"

.PP
Jogador Atual\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIe\fP Apontador para o estado Esta função diz qual é o jogador a efectuar a jogada\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
O jogador atual 
.RE
.PP

.SS "\fBHOUSE\fP get_house (\fBSTATE\fP *, \fBCOORDINATE\fP)"

.PP
Devolve o valor de uma casa\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIe\fP Apontador para o estado 
.br
\fIc\fP A coordenada 
.RE
.PP
\fBRetorna\fP
.RS 4
O valor da casa 
.RE
.PP

.SS "int get_num_moves (\fBSTATE\fP *)"

.PP
Número de jogadas\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIe\fP Apontador para o estado Esta função calcula qual o número total das jogadas\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Número total de jogadas 
.RE
.PP

.SS "\fBCOORDINATE\fP get_previous_move (\fBSTATE\fP *)"

.PP
Jogada anterior\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIe\fP Apontador para o estado Esta função diz qual foi a coordenada da jogada anterior\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
A coordenada da jogada anterior 
.RE
.PP

.SS "\fBSTATE\fP* starting_state ()"

.PP
Inicializa o valor do estado Esta função inicializa o valor do estado\&. Isso implica o tabuleiro ser colocado na posição inicial e todos os campos do estado estarem com o valor por omissão\&. 
.PP
\fBRetorna\fP
.RS 4
O novo estado 
.RE
.PP

.SS "void update_previous_move (\fBSTATE\fP *, \fBCOORDINATE\fP)"

.PP
Atualiza jogada anterior\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIe\fP Apontador para o estado 
.br
\fIc\fP A coordenada Esta função altera a coordenada da jogada anterior no estado para a coordenada nova\&. 
.RE
.PP

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para SlimeTrail a partir do código fonte\&.
