.TH "md__c_1__users__miguel__gomes__documents__miguel__uni__l_i2-_t_p1-_g05__r_e_a_d_m_e" 3 "Sexta, 20 de Março de 2020" "Version 0.1" "SlimeTrail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users__miguel__gomes__documents__miguel__uni__l_i2-_t_p1-_g05__r_e_a_d_m_e \- Rastros - LI2 
Um jogo baseado no jogo 'Rastros', criado em C no âmbito da cadeira de Laboratórios de Informática II 2019/2020, no mestrado integrado em Engenharia Informática da Universidade do Minho\&.
.PP
Turno - PL1
.PP
Grupo - 005
.PP
Elementos :
.IP "\(bu" 2
A93294 - Pedro Miguel Rodrigues Gomes
.IP "\(bu" 2
A93216 - Guilherme Lima Barros Gomes Fernandes
.PP
.SH "SlimeTrail - LI2"
.PP
A game based on the game 'SlimeTrail', created in C under the course of Computer Laboratories II 2019/2020, in the integrated master's degree in Software Engineering at the University of Minho\&.
.PP
Turn - PL1
.PP
Group - 005
.PP
Elements :
.IP "\(bu" 2
A93294 - Pedro Miguel Rodrigues Gomes
.IP "\(bu" 2
A93216 - Guilherme Lima Barros Gomes Fernandes 
.PP

