.TH "md__c_1__users__miguel__gomes__documents__miguel__uni__l_i2-_t_p1-_g05__report" 3 "Sexta, 20 de Março de 2020" "Version 0.1" "SlimeTrail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users__miguel__gomes__documents__miguel__uni__l_i2-_t_p1-_g05__report \- Guião 5: 
Durante esta semana realizamos as actividades propostas,chegando até a adiantar mais algumas, como a função que verifica se a jogada é válida (que ainda não se encontra completamente funcional), e a função que coloca a peça preta no local atual da peça branca\&. Não foram encontradas grandes dificuldades, apenas tivemos que pesquisar algumas informações de como operar em structs, de aprender como utilizar a função do malloc() para inicializar a matriz do tabuleiro\&. 
